language: python
env:
    - TOX_ENV=py35
    - TOX_ENV=flake8
python: 3.5
install:
  - pip install -r pipenv.txt -r tox.txt
script: tox -e $TOX_ENV
after_success:
  - pip install coveralls
  - coveralls
